[package]
name = "thecity"
version = "0.1.0"
authors = ["Daniel Hauser <daniel.hauser@liwest.at>"]
edition = "2018"

[dependencies]
sdl2 = "0.35.2"
ncollide3d = "0.33.0"
rayon = "1.0.2"
wavefront_obj = "10.0.0"

[profile.release]
opt-level = 3
lto = true